---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может удалять товары из корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь имеет возможность оформить заказ
   - Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь не должен иметь возможность указывать отрицательное значение цены
  - При нажатии на главном экране на кнопку "В корзину", кнопка должна изменяться на количество
  - Пользователь не может редактировать описание товаров
  - В фильтрах производителя товаров должна быть полоса прокрутки
  - Названия категорий в русскоязычной версии сайта также должно быть на русском языке
  - В категории товаров должна быть возможность сброса выбора категории
  - Пользователь должен иметь возможноть редактировать количество товаров в корзине
